### ISSUE TITLE
맥+크롬+한글 키워드 직접 입력시 오류

### ISSUE THREAD

**Issue by Jlnus** [boostcampaitech4lv23nlp2/final-project-level3-nlp-10#32]
## 🐛 Bug Report

- 맥os에서 크롬 브라우저를 이용하여 한글 입력시 마지막 글자가 한번 더 입력됨
<img width="743" alt="image" src="https://user-images.githubusercontent.com/69241185/217186987-b02f0187-193f-4150-8d88-62c581673dd7.png">

## 🔬 How To Reproduce

- 맥+크롬 이용시 글자입력 후 띄어쓰기하고 엔터하도록 권고 문구 추가 등

### Environment

- OS: macOS
- chrome 브라우저

## 📎 Additional context

#29

**Comment by EJueon** [comment]
Mac OS에서 Chrome 사용 시에만 발생하는 오류로 본 어플리케이션 자체의 문제가 아니기 때문에 해결할 수 없다고 판단. issue를 닫습니다.
